/**
 * Site config type definition — drives the template rendering.
 * Generated by the pipeline, stored in Site.previewConfig / Site.liveConfig.
 */
export interface SiteConfig {
  meta: {
    projectId: string;
    siteId: string | null;
    clientName: string;
    templateFamily: string;
    generatedAt: string;
  };
  branding: {
    businessName: string;
    logoUrl: string | null;
    phone: string;
    email: string;
    address: string;
    officeHours: string;
    socialLinks: { platform: string; url: string }[];
  };
  theme: {
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    backgroundColor: string;
    textColor: string;
    fontHeading: string;
    fontBody: string;
  };
  layout: {
    showHero: boolean;
    showServices: boolean;
    showAbout: boolean;
    showTestimonials: boolean;
    showFaq: boolean;
    showContact: boolean;
    showFooter: boolean;
  };
  hero: {
    headline: string;
    subheadline: string;
    ctaText: string;
    ctaSecondaryText: string;
  };
  services: {
    title: string;
    subtitle: string;
    items: { name: string; description: string }[];
  };
  about: {
    title: string;
    description: string;
    highlights: string[];
  };
  testimonials: {
    title: string;
    items: { text: string; author: string; role?: string }[];
  };
  faq: {
    title: string;
    items: { question: string; answer: string }[];
  };
  contact: {
    title: string;
    subtitle: string;
    ctaText: string;
  };
  footer: {
    tagline: string;
    copyright: string;
    businessName: string;
    phone: string;
    email: string;
    address: string;
  };
}
